### ISSUE TITLE
Missing argument at index 2

### ISSUE THREAD

**Issue by iampeterbanjo** [titpetric/books#1]
I'm working through the exercises in the book but when I try and run the `docker run` script on the `hello_world.go` file I get the following error message

`test: Missing argument at index 2`
`test: Missing argument at index 2`

**Comment by titpetric** [comment]
There's a "run" script provided in the same chapter1 folder, which works for me:

~~~
$ ./run
== go run hello_world.go ==
Hello world!
~~~

Which exact docker run command are you running? I'll check the ch1 in the book, perhaps I just need to fix some slightly older example.

**Comment by iampeterbanjo** [comment]
In ch1 under "Setting up a runner for your Go programs" there are these instructions - 

```
$ docker run --net=party -p 8080:80 --rm=true -it -v `pwd`:/go/src/app -w /go/sr\
c/app golang go "$@"

```

> Save this code snippet as the file ‘go’, make it executable and copy it to your execution path (usually
> /usr/local/bin is reserved for things like this).

Using that code snippet to run the `hello_world.go` is causing the error. I have put it in my path but I run it as `docker-go` so that I can switch between the two. Using the default `go` prints `Hello World`.

With the new script in `../shell/common.sh/` there are no errors but `Hello World` is not being printed to the screen.

In terms of my setup I'm running Linux Mint 17 and Fish shell but I have also tried the commands in bash with the same results.

**Comment by titpetric** [comment]
Please try running it with the script provided, like I have (../shell/go). Most likely, the #!/bin/bash line is needed and I'll have to amend the instructions in the book.

**Comment by iampeterbanjo** [comment]
You're right - I added `#!/bin/bash` to the docker script and now both it and `./run` are printing `Hello World` in bash and fish shell. For consistency I amended the `run` script as follows:
```

#!/bin/bash
source ../shell/common.sh

APP="foundations"

FILES=$(ls *.go | sort)
for FILE in $FILES; do
	docker-go.sh run $FILE
done
```

Thanks for your help
