### ISSUE TITLE
Chapter4b JWT

### ISSUE THREAD

**Issue by NapalmCodes** [titpetric/books#2]
Where exactly is this mentioned in your book?  One of the main reasons I purchased was for instruction around JWT utilization but if you search the book for JWT there are only two results?  What is considered Chapter4b?

**Comment by titpetric** [comment]
Hey,

thanks for the heads up. It seems Leanpub ate at least one of the recent
book updates. I'm going to investigate it and republish the book shortly.

Until then, the chapter about JWT is actually available as a blog article:
https://scene-si.org/2018/05/08/protecting-api-access-with-jwt/
(chapter-4b-jwt folder containes the cited example code)

I apologize for any inconvenience, let me know if there's something I can
do, or some subject you'd like covered in more detail. I'm currently
updating the book for 2018 state of things, so now would be the time to add
some things as well :)

Best,
Tit

**Comment by NapalmCodes** [comment]
Tit,

Thanks for clarifying what was going on.  That is the single most thing I am struggling with for go development (probably because I come from a .net background where most of the logic is for JWT/Token based authentication is abstracted away by Microsoft).  Security is the single biggest thing I would like to get more information on, as that is the only way I will be able to make a case for Go in the enterprise.  Correct me if I am wrong but when you release the new update on Leanpub I should be able to download that without re-purchase right?

Thanks again!

**Comment by titpetric** [comment]
Yes, you're correct. Once you bought the book, you're getting the updates without having to pay for them again. I do rely on regular book sales to keep updating the book, and knowing what people are looking at is helpful in that regard. I'll think about how security could tie into the book subjects, thanks for the suggestion!
